#import "RunPwshPanelView.h"
#import "RunPwshLocalization.h"
// Generated by `swift build`'s -emit-objc-header-path (see
// swift/RunPwshTerminalBridge/Package.swift) — declares RunPwshTerminalBridge,
// the @objc wrapper around SwiftTerm's LocalProcessTerminalView. Not checked
// into git (it's a build product); CMakeLists.txt adds its containing
// directory to this target's include path.
#import "RunPwshTerminalBridge-Swift.h"

@interface RunPwshPanelView ()
@end

@implementation RunPwshPanelView {
    NSButton *_runScriptButton;
    NSButton *_runSelectionButton;
    NSButton *_stopButton;
    NSButton *_newSessionButton;
    NSButton *_openTerminalButton;
    NSTextField *_statusLabel;

    NSView *_banner;
    NSTextField *_bannerLabel;
    NSButton *_bannerInstallButton;
    NSLayoutConstraint *_bannerHeightConstraint;

    RunPwshTerminalBridge *_terminalBridge;
    BOOL _hasSession;

    // v3.1.4: set right after spawning a *brand-new* session, cleared by
    // the very next -runText: call — see -runText:'s doc comment for what
    // this drives (a belt-and-suspenders extra Enter keystroke for that
    // first command only).
    BOOL _needsStartupSafetyNet;
}

#pragma mark - Init / layout

- (instancetype)initWithFrame:(NSRect)frameRect {
    self = [super initWithFrame:frameRect];
    if (self) {
        [self buildUI];

        __weak RunPwshPanelView *weakSelf = self;
        [RunPwshLocalization observeLanguageChangesWithBlock:^{
            [weakSelf relocalizeUI];
        }];
    }
    return self;
}

- (void)buildUI {
    self.translatesAutoresizingMaskIntoConstraints = NO;

    // ── Toolbar ──────────────────────────────────────────────────────────
    NSView *toolbar = [[NSView alloc] init];
    toolbar.translatesAutoresizingMaskIntoConstraints = NO;
    [self addSubview:toolbar];

    _runScriptButton = [self toolbarButtonWithSymbol:@"play.fill"
                                              tooltip:RPLoc(@"Script ausführen", @"Run Script")
                                               action:@selector(runScriptClicked:)];
    _runScriptButton.contentTintColor = [NSColor systemGreenColor];

    _runSelectionButton = [self toolbarButtonWithSymbol:@"play.rectangle"
                                                 tooltip:RPLoc(@"Auswahl ausführen", @"Run Selection")
                                                  action:@selector(runSelectionClicked:)];
    _runSelectionButton.contentTintColor = [NSColor systemGreenColor];

    _stopButton = [self toolbarButtonWithSymbol:@"stop.fill"
                                         tooltip:RPLoc(@"Aktuellen Befehl abbrechen", @"Interrupt current command")
                                          action:@selector(stopClicked:)];
    _stopButton.contentTintColor = [NSColor systemGrayColor];
    _stopButton.enabled = NO;

    _newSessionButton = [self toolbarButtonWithSymbol:@"arrow.triangle.2.circlepath"
                                               tooltip:RPLoc(@"Neue Sitzung starten", @"Start New Session")
                                                action:@selector(newSessionClicked:)];
    _newSessionButton.contentTintColor = [NSColor systemOrangeColor];

    _openTerminalButton = [self toolbarButtonWithSymbol:@"terminal"
                                                 tooltip:RPLoc(@"Pwsh in Terminal starten", @"Start Pwsh in Terminal")
                                                  action:@selector(openTerminalClicked:)];
    _openTerminalButton.contentTintColor = [NSColor systemBlueColor];

    for (NSButton *b in @[_runScriptButton, _runSelectionButton, _stopButton, _newSessionButton, _openTerminalButton]) {
        [toolbar addSubview:b];
    }

    _statusLabel = [NSTextField labelWithString:@""];
    _statusLabel.translatesAutoresizingMaskIntoConstraints = NO;
    _statusLabel.font = [NSFont systemFontOfSize:11];
    _statusLabel.textColor = [NSColor secondaryLabelColor];
    _statusLabel.lineBreakMode = NSLineBreakByTruncatingMiddle;
    [toolbar addSubview:_statusLabel];

    NSDictionary *toolbarViews = NSDictionaryOfVariableBindings(
        _runScriptButton, _runSelectionButton, _stopButton, _newSessionButton, _openTerminalButton, _statusLabel);
    [toolbar addConstraints:[NSLayoutConstraint constraintsWithVisualFormat:
        @"H:|-4-[_runScriptButton(26)]-4-[_runSelectionButton(26)]-4-[_stopButton(26)]-4-[_newSessionButton(26)]-10-[_openTerminalButton(26)]-10-[_statusLabel(>=60)]-4-|"
        options:NSLayoutFormatAlignAllCenterY metrics:nil views:toolbarViews]];
    [toolbar addConstraints:[NSLayoutConstraint constraintsWithVisualFormat:@"V:|-3-[_runScriptButton(26)]-3-|"
        options:0 metrics:nil views:toolbarViews]];

    // ── Install banner (hidden by default) ─────────────────────────────
    _banner = [[NSView alloc] init];
    _banner.translatesAutoresizingMaskIntoConstraints = NO;
    _banner.wantsLayer = YES;
    _banner.layer.backgroundColor = [NSColor colorWithCalibratedRed:0.98 green:0.85 blue:0.35 alpha:0.25].CGColor;
    [self addSubview:_banner];

    _bannerLabel = [NSTextField wrappingLabelWithString:@""];
    _bannerLabel.translatesAutoresizingMaskIntoConstraints = NO;
    _bannerLabel.font = [NSFont systemFontOfSize:11];
    [_banner addSubview:_bannerLabel];

    _bannerInstallButton = [[NSButton alloc] init];
    _bannerInstallButton.translatesAutoresizingMaskIntoConstraints = NO;
    _bannerInstallButton.bezelStyle = NSBezelStyleRounded;
    _bannerInstallButton.title = RPLoc(@"Installieren via Homebrew", @"Install via Homebrew");
    _bannerInstallButton.target = self;
    _bannerInstallButton.action = @selector(installClicked:);
    [_banner addSubview:_bannerInstallButton];

    NSDictionary *bannerViews = NSDictionaryOfVariableBindings(_bannerLabel, _bannerInstallButton);
    [_banner addConstraints:[NSLayoutConstraint constraintsWithVisualFormat:
        @"H:|-8-[_bannerLabel]-8-[_bannerInstallButton]-8-|"
        options:NSLayoutFormatAlignAllCenterY metrics:nil views:bannerViews]];
    [_banner addConstraints:[NSLayoutConstraint constraintsWithVisualFormat:@"V:|-6-[_bannerLabel]-6-|"
        options:0 metrics:nil views:bannerViews]];

    _bannerHeightConstraint = [NSLayoutConstraint constraintWithItem:_banner
        attribute:NSLayoutAttributeHeight relatedBy:NSLayoutRelationEqual
        toItem:nil attribute:NSLayoutAttributeNotAnAttribute multiplier:1 constant:0];
    _bannerHeightConstraint.active = YES;
    [_banner addConstraint:_bannerHeightConstraint];

    // ── Embedded terminal ────────────────────────────────────────────────
    // Replaces the old read-only NSTextView console + separate input field
    // (pre-2.0.0): RunPwshTerminalBridge wraps SwiftTerm's
    // LocalProcessTerminalView, a real terminal widget that owns its own
    // pty, renders full VT100/ANSI output, and forwards typed keystrokes
    // (including arrow keys / tab-completion / line history) directly to
    // the child process itself — exactly what PSReadLine-driven interactive
    // prompts (Connect-AzAccount pickers, Get-Credential, Enter-PSSession's
    // credential fallback) need, and what a plain NSTextView fundamentally
    // couldn't provide (see CHANGELOG 2.0.0).
    _terminalBridge = [[RunPwshTerminalBridge alloc] init];
    NSView *terminalView = _terminalBridge.view;
    terminalView.translatesAutoresizingMaskIntoConstraints = NO;
    [self addSubview:terminalView];

    __weak RunPwshPanelView *weakSelfForExit = self;
    _terminalBridge.onProcessExited = ^(int32_t exitCode) {
        RunPwshPanelView *strongSelf = weakSelfForExit;
        if (!strongSelf) return;
        // Since v3.0.0 this fires when the whole persistent session ends
        // (user typed `exit`, it crashed, or -killSession was called) —
        // NOT after every individual "Run Script"/"Run Selection", since
        // those now just type into the same long-lived session instead of
        // spawning their own process. See -runText: / -ensureSessionStarted...
        [strongSelf feedText:[NSString stringWithFormat:@"\n[%@ %d]\n",
            RPLoc(@"Sitzung beendet, Exit-Code", @"Session ended, exit code"), exitCode]];
        [strongSelf setSessionActive:NO];
        if ([strongSelf.delegate respondsToSelector:@selector(runPwshPanelViewProcessDidExit:exitCode:)]) {
            [strongSelf.delegate runPwshPanelViewProcessDidExit:strongSelf exitCode:exitCode];
        }
    };

    NSDictionary *rootViews = NSDictionaryOfVariableBindings(toolbar, _banner, terminalView);
    [self addConstraints:[NSLayoutConstraint constraintsWithVisualFormat:@"H:|[toolbar]|" options:0 metrics:nil views:rootViews]];
    [self addConstraints:[NSLayoutConstraint constraintsWithVisualFormat:@"H:|[_banner]|" options:0 metrics:nil views:rootViews]];
    [self addConstraints:[NSLayoutConstraint constraintsWithVisualFormat:@"H:|[terminalView]|" options:0 metrics:nil views:rootViews]];
    [self addConstraints:[NSLayoutConstraint constraintsWithVisualFormat:
        @"V:|[toolbar(32)][_banner][terminalView]|" options:0 metrics:nil views:rootViews]];
}

/// Same technique as FinderPanelView's -toolbarButtonWithSymbol:tooltip:action:
/// (SF Symbol as a template image, tinted automatically for light/dark mode)
/// — deliberately not custom PNG assets; see the Finder plugin's CHANGELOG
/// 1.3.0/1.3.1 for why that was tried and reverted for panel-internal
/// buttons. Custom PNGs are only used for RunPwsh's single main
/// toolbar/menu-band icon (resources/toolbar.png, registered via
/// NPPM_ADDTOOLBARICON_FORDARKMODE in RunPwshPlugin.mm), matching how the
/// Finder plugin draws that one distinction.
- (NSButton *)toolbarButtonWithSymbol:(NSString *)symbolName tooltip:(NSString *)tooltip action:(SEL)action {
    NSButton *b = [[NSButton alloc] init];
    b.translatesAutoresizingMaskIntoConstraints = NO;
    NSImage *img = [NSImage imageWithSystemSymbolName:symbolName accessibilityDescription:tooltip];
    if (img) {
        NSImageSymbolConfiguration *cfg = [NSImageSymbolConfiguration configurationWithPointSize:14
                                                                                          weight:NSFontWeightRegular];
        img = [img imageWithSymbolConfiguration:cfg];
    }
    b.image = img;
    b.imagePosition = NSImageOnly;
    b.imageScaling = NSImageScaleProportionallyDown;
    b.bezelStyle = NSBezelStyleTexturedRounded;
    b.bordered = NO;
    b.toolTip = tooltip;
    b.target = self;
    b.action = action;
    return b;
}

#pragma mark - Localization

- (void)relocalizeUI {
    _runScriptButton.toolTip = RPLoc(@"Script ausführen", @"Run Script");
    _runSelectionButton.toolTip = RPLoc(@"Auswahl ausführen", @"Run Selection");
    _stopButton.toolTip = RPLoc(@"Aktuellen Befehl abbrechen", @"Interrupt current command");
    _newSessionButton.toolTip = RPLoc(@"Neue Sitzung starten", @"Start New Session");
    _openTerminalButton.toolTip = RPLoc(@"Pwsh in Terminal starten", @"Start Pwsh in Terminal");
    _bannerInstallButton.title = RPLoc(@"Installieren via Homebrew", @"Install via Homebrew");
}

#pragma mark - Public API

- (BOOL)hasSession {
    return _hasSession;
}

- (void)ensureSessionStartedWithExecutable:(NSString *)executable
                                  arguments:(NSArray<NSString *> *)arguments
                           currentDirectory:(nullable NSString *)currentDirectory
                                 completion:(void (^)(void))completion {
    if (_hasSession) {
        if (completion) completion();
        return;
    }
    [self setSessionActive:YES];
    _needsStartupSafetyNet = YES;
    [_terminalBridge startWithExecutable:executable args:arguments currentDirectory:currentDirectory];
    // Merely spawning the process isn't the same as pwsh actually being
    // ready to read input: module loading and PSReadLine attaching to the
    // pty (switching it from cooked to raw mode) takes a moment after
    // startProcess() returns. -runText: right away races that window (see
    // its doc comment in the header for the exact symptom this caused) —
    // give it a short grace period before letting the caller type anything.
    // (v3.1.4: this alone still isn't fully reliable — startup time varies
    // by machine — so -runText: also arms a follow-up safety-net keystroke
    // for the very first command; see _needsStartupSafetyNet above.)
    if (completion) {
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.6 * NSEC_PER_SEC)),
                        dispatch_get_main_queue(), completion);
    }
}

- (void)runText:(NSString *)text {
    // A real Enter keypress sends "\r" (CR) over a pty, not "\n" (LF) — and
    // once PSReadLine attaches and puts the pty into raw mode, only "\r" is
    // actually recognized as "submit the current line"; a bare "\n" just
    // gets inserted as a literal character and never executes anything
    // (root cause of a user-reported bug, 2026-08-28: selected text/lines
    // got typed into the terminal but the command just sat there,
    // un-invoked, with no output). This also matters for every *embedded*
    // newline in a multi-line selection, not just the final terminator —
    // each one needs to behave like its own Enter press for that line to
    // actually run instead of just being appended to a growing multi-line
    // literal. Normalize everything to "\r" for this reason.
    NSString *toType = [text stringByReplacingOccurrencesOfString:@"\r\n" withString:@"\r"];
    toType = [toType stringByReplacingOccurrencesOfString:@"\n" withString:@"\r"];
    if (![toType hasSuffix:@"\r"]) {
        toType = [toType stringByAppendingString:@"\r"];
    }
    [_terminalBridge typeText:toType];

    // v3.1.4: the grace period in -ensureSessionStartedWithExecutable:...
    // still isn't fully reliable on its own — real-world pwsh startup time
    // varies (module loading, disk cache state, machine speed), and a user
    // report confirmed the *very first* Run against a freshly-started
    // session could still lose this race even with that delay in place: the
    // command above got typed correctly but PSReadLine wasn't listening yet
    // to treat the trailing "\r" as Enter, so it just sat there unsubmitted.
    // Only for that first command, arm one extra bare "\r" a bit further
    // out: if the race really was lost, this submits whatever's still
    // sitting in PSReadLine's now-attached raw-mode buffer (i.e. our
    // command); if the first "\r" actually landed fine, this is a harmless
    // no-op Enter press on an empty prompt line.
    if (_needsStartupSafetyNet) {
        _needsStartupSafetyNet = NO;
        __weak RunPwshTerminalBridge *weakBridge = _terminalBridge;
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(1.5 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
            [weakBridge typeText:@"\r"];
        });
    }
}

- (void)interruptSession {
    [_terminalBridge interrupt];
}

- (void)killSession {
    [_terminalBridge killSession];
}

- (void)feedText:(NSString *)text {
    if (![NSThread isMainThread]) {
        dispatch_async(dispatch_get_main_queue(), ^{ [self feedText:text]; });
        return;
    }
    NSString *normalized = [text stringByReplacingOccurrencesOfString:@"\r\n" withString:@"\n"];
    normalized = [normalized stringByReplacingOccurrencesOfString:@"\n" withString:@"\r\n"];
    [_terminalBridge feedWithText:normalized];
}

- (void)setSessionActive:(BOOL)active {
    _hasSession = active;
    _stopButton.enabled = active;
    _stopButton.contentTintColor = active ? [NSColor systemRedColor] : [NSColor systemGrayColor];
}

- (void)showInstallBanner:(BOOL)show reason:(nullable NSString *)reason canInstall:(BOOL)canInstall {
    if (show) {
        _bannerLabel.stringValue = reason ?: RPLoc(@"PowerShell (pwsh) wurde nicht gefunden.", @"PowerShell (pwsh) was not found.");
        _bannerInstallButton.hidden = !canInstall;
    }
    _bannerHeightConstraint.constant = show ? 40 : 0;
    _banner.hidden = !show;
    [self setNeedsLayout:YES];
}

- (void)setStatusText:(NSString *)text {
    _statusLabel.stringValue = text ?: @"";
}

#pragma mark - Actions

- (void)runScriptClicked:(id)sender {
    if ([self.delegate respondsToSelector:@selector(runPwshPanelViewDidRequestRunScript:)]) {
        [self.delegate runPwshPanelViewDidRequestRunScript:self];
    }
}

- (void)runSelectionClicked:(id)sender {
    if ([self.delegate respondsToSelector:@selector(runPwshPanelViewDidRequestRunSelection:)]) {
        [self.delegate runPwshPanelViewDidRequestRunSelection:self];
    }
}

- (void)stopClicked:(id)sender {
    if ([self.delegate respondsToSelector:@selector(runPwshPanelViewDidRequestStop:)]) {
        [self.delegate runPwshPanelViewDidRequestStop:self];
    }
}

- (void)newSessionClicked:(id)sender {
    if ([self.delegate respondsToSelector:@selector(runPwshPanelViewDidRequestNewSession:)]) {
        [self.delegate runPwshPanelViewDidRequestNewSession:self];
    }
}

- (void)openTerminalClicked:(id)sender {
    if ([self.delegate respondsToSelector:@selector(runPwshPanelViewDidRequestOpenTerminal:)]) {
        [self.delegate runPwshPanelViewDidRequestOpenTerminal:self];
    }
}

- (void)installClicked:(id)sender {
    if ([self.delegate respondsToSelector:@selector(runPwshPanelViewDidRequestInstallPwsh:)]) {
        [self.delegate runPwshPanelViewDidRequestInstallPwsh:self];
    }
}

@end
