#import "RunPwshPanelView.h"
#import "RunPwshLocalization.h"
#import "RunPwshSession.h"
// Generated by `swift build`'s -emit-objc-header-path (see
// swift/RunPwshTerminalBridge/Package.swift) — declares RunPwshTerminalBridge,
// the @objc wrapper around SwiftTerm's LocalProcessTerminalView. Not checked
// into git (it's a build product); CMakeLists.txt adds its containing
// directory to this target's include path.
#import "RunPwshTerminalBridge-Swift.h"

@interface RunPwshPanelView ()
@end

/// Adapts the Swift bridge to RunPwshSessionTransport.
@interface RunPwshBridgeTransport : NSObject <RunPwshSessionTransport>
@property (nonatomic, strong) RunPwshTerminalBridge *bridge;
@property (nonatomic, copy, nullable) void (^onPrompt)(void);
@property (nonatomic, copy, nullable) void (^onExit)(int32_t exitCode);
- (instancetype)initWithBridge:(RunPwshTerminalBridge *)bridge;
@end

@implementation RunPwshBridgeTransport
- (instancetype)initWithBridge:(RunPwshTerminalBridge *)bridge {
    if ((self = [super init])) {
        _bridge = bridge;
        __weak RunPwshBridgeTransport *weakSelf = self;
        bridge.onPrompt = ^{ if (weakSelf.onPrompt) weakSelf.onPrompt(); };
        bridge.onProcessExited = ^(int32_t code) { if (weakSelf.onExit) weakSelf.onExit(code); };
    }
    return self;
}
- (void)startWithExecutable:(NSString *)e args:(NSArray<NSString *> *)a currentDirectory:(NSString *)c {
    [_bridge startWithExecutable:e args:a currentDirectory:c];
}
- (void)typeText:(NSString *)t { [_bridge typeText:t]; }
- (void)interrupt { [_bridge interrupt]; }
- (void)kill { [_bridge killSession]; }
@end

@implementation RunPwshPanelView {
    NSButton *_runScriptButton;
    NSButton *_runSelectionButton;
    NSButton *_stopButton;
    NSButton *_restartButton;
    NSTextField *_statusLabel;

    NSView *_banner;
    NSTextField *_bannerLabel;
    NSButton *_bannerInstallButton;
    NSLayoutConstraint *_bannerHeightConstraint;

    RunPwshTerminalBridge *_terminalBridge;
    RunPwshSession *_session;
}

#pragma mark - Init / layout

- (instancetype)initWithFrame:(NSRect)frameRect {
    self = [super initWithFrame:frameRect];
    if (self) {
        [self buildUI];

        __weak RunPwshPanelView *weakSelf = self;
        [RunPwshLocalization observeLanguageChangesWithBlock:^{
            [weakSelf relocalizeUI];
        }];
    }
    return self;
}

- (void)buildUI {
    self.translatesAutoresizingMaskIntoConstraints = NO;

    // ── Toolbar ──────────────────────────────────────────────────────────
    NSView *toolbar = [[NSView alloc] init];
    toolbar.translatesAutoresizingMaskIntoConstraints = NO;
    [self addSubview:toolbar];

    _runScriptButton = [self toolbarButtonWithSymbol:@"play.fill"
                                              tooltip:RPLoc(@"Script ausführen", @"Run Script")
                                               action:@selector(runScriptClicked:)];
    _runScriptButton.contentTintColor = [NSColor systemGreenColor];

    _runSelectionButton = [self toolbarButtonWithSymbol:@"play.rectangle"
                                                 tooltip:RPLoc(@"Auswahl ausführen", @"Run Selection")
                                                  action:@selector(runSelectionClicked:)];
    _runSelectionButton.contentTintColor = [NSColor systemGreenColor];

    _stopButton = [self toolbarButtonWithSymbol:@"stop.fill"
                                         tooltip:RPLoc(@"Aktuellen Befehl abbrechen", @"Interrupt current command")
                                          action:@selector(stopClicked:)];
    _stopButton.contentTintColor = [NSColor systemGrayColor];
    _stopButton.enabled = NO;

    _restartButton = [self toolbarButtonWithSymbol:@"arrow.triangle.2.circlepath"
                                           tooltip:RPLoc(@"Sitzung neu starten", @"Restart Session")
                                            action:@selector(restartClicked:)];
    _restartButton.contentTintColor = [NSColor systemOrangeColor];

    for (NSButton *b in @[_runScriptButton, _runSelectionButton, _stopButton, _restartButton]) {
        [toolbar addSubview:b];
    }

    _statusLabel = [NSTextField labelWithString:@""];
    _statusLabel.translatesAutoresizingMaskIntoConstraints = NO;
    _statusLabel.font = [NSFont systemFontOfSize:11];
    _statusLabel.textColor = [NSColor secondaryLabelColor];
    _statusLabel.lineBreakMode = NSLineBreakByTruncatingMiddle;
    [toolbar addSubview:_statusLabel];

    NSDictionary *toolbarViews = NSDictionaryOfVariableBindings(
        _runScriptButton, _runSelectionButton, _stopButton, _restartButton, _statusLabel);
    [toolbar addConstraints:[NSLayoutConstraint constraintsWithVisualFormat:
        @"H:|-4-[_runScriptButton(26)]-4-[_runSelectionButton(26)]-4-[_stopButton(26)]-4-[_restartButton(26)]-10-[_statusLabel(>=60)]-4-|"
        options:NSLayoutFormatAlignAllCenterY metrics:nil views:toolbarViews]];
    [toolbar addConstraints:[NSLayoutConstraint constraintsWithVisualFormat:@"V:|-3-[_runScriptButton(26)]-3-|"
        options:0 metrics:nil views:toolbarViews]];

    // ── Install banner (hidden by default) ─────────────────────────────
    _banner = [[NSView alloc] init];
    _banner.translatesAutoresizingMaskIntoConstraints = NO;
    _banner.wantsLayer = YES;
    _banner.layer.backgroundColor = [NSColor colorWithCalibratedRed:0.98 green:0.85 blue:0.35 alpha:0.25].CGColor;
    [self addSubview:_banner];

    _bannerLabel = [NSTextField wrappingLabelWithString:@""];
    _bannerLabel.translatesAutoresizingMaskIntoConstraints = NO;
    _bannerLabel.font = [NSFont systemFontOfSize:11];
    [_banner addSubview:_bannerLabel];

    _bannerInstallButton = [[NSButton alloc] init];
    _bannerInstallButton.translatesAutoresizingMaskIntoConstraints = NO;
    _bannerInstallButton.bezelStyle = NSBezelStyleRounded;
    _bannerInstallButton.title = RPLoc(@"Installieren via Homebrew", @"Install via Homebrew");
    _bannerInstallButton.target = self;
    _bannerInstallButton.action = @selector(installClicked:);
    [_banner addSubview:_bannerInstallButton];

    NSDictionary *bannerViews = NSDictionaryOfVariableBindings(_bannerLabel, _bannerInstallButton);
    [_banner addConstraints:[NSLayoutConstraint constraintsWithVisualFormat:
        @"H:|-8-[_bannerLabel]-8-[_bannerInstallButton]-8-|"
        options:NSLayoutFormatAlignAllCenterY metrics:nil views:bannerViews]];
    [_banner addConstraints:[NSLayoutConstraint constraintsWithVisualFormat:@"V:|-6-[_bannerLabel]-6-|"
        options:0 metrics:nil views:bannerViews]];

    _bannerHeightConstraint = [NSLayoutConstraint constraintWithItem:_banner
        attribute:NSLayoutAttributeHeight relatedBy:NSLayoutRelationEqual
        toItem:nil attribute:NSLayoutAttributeNotAnAttribute multiplier:1 constant:0];
    _bannerHeightConstraint.active = YES;
    [_banner addConstraint:_bannerHeightConstraint];

    // ── Embedded terminal ────────────────────────────────────────────────
    // Replaces the old read-only NSTextView console + separate input field
    // (pre-2.0.0): RunPwshTerminalBridge wraps SwiftTerm's
    // LocalProcessTerminalView, a real terminal widget that owns its own
    // pty, renders full VT100/ANSI output, and forwards typed keystrokes
    // (including arrow keys / tab-completion / line history) directly to
    // the child process itself — exactly what PSReadLine-driven interactive
    // prompts (Connect-AzAccount pickers, Get-Credential, Enter-PSSession's
    // credential fallback) need, and what a plain NSTextView fundamentally
    // couldn't provide (see CHANGELOG 2.0.0).
    _terminalBridge = [[RunPwshTerminalBridge alloc] init];
    NSView *terminalView = _terminalBridge.view;
    terminalView.translatesAutoresizingMaskIntoConstraints = NO;
    [self addSubview:terminalView];

    NSDictionary *rootViews = NSDictionaryOfVariableBindings(toolbar, _banner, terminalView);
    [self addConstraints:[NSLayoutConstraint constraintsWithVisualFormat:@"H:|[toolbar]|" options:0 metrics:nil views:rootViews]];
    [self addConstraints:[NSLayoutConstraint constraintsWithVisualFormat:@"H:|[_banner]|" options:0 metrics:nil views:rootViews]];
    [self addConstraints:[NSLayoutConstraint constraintsWithVisualFormat:@"H:|[terminalView]|" options:0 metrics:nil views:rootViews]];
    [self addConstraints:[NSLayoutConstraint constraintsWithVisualFormat:
        @"V:|[toolbar(32)][_banner][terminalView]|" options:0 metrics:nil views:rootViews]];
}

/// Same technique as FinderPanelView's -toolbarButtonWithSymbol:tooltip:action:
/// (SF Symbol as a template image, tinted automatically for light/dark mode)
/// — deliberately not custom PNG assets; see the Finder plugin's CHANGELOG
/// 1.3.0/1.3.1 for why that was tried and reverted for panel-internal
/// buttons. Custom PNGs are only used for RunPwsh's single main
/// toolbar/menu-band icon (resources/toolbar.png, registered via
/// NPPM_ADDTOOLBARICON_FORDARKMODE in RunPwshPlugin.mm), matching how the
/// Finder plugin draws that one distinction.
- (NSButton *)toolbarButtonWithSymbol:(NSString *)symbolName tooltip:(NSString *)tooltip action:(SEL)action {
    NSButton *b = [[NSButton alloc] init];
    b.translatesAutoresizingMaskIntoConstraints = NO;
    NSImage *img = [NSImage imageWithSystemSymbolName:symbolName accessibilityDescription:tooltip];
    if (img) {
        NSImageSymbolConfiguration *cfg = [NSImageSymbolConfiguration configurationWithPointSize:14
                                                                                          weight:NSFontWeightRegular];
        img = [img imageWithSymbolConfiguration:cfg];
    }
    b.image = img;
    b.imagePosition = NSImageOnly;
    b.imageScaling = NSImageScaleProportionallyDown;
    b.bezelStyle = NSBezelStyleTexturedRounded;
    b.bordered = NO;
    b.toolTip = tooltip;
    b.target = self;
    b.action = action;
    return b;
}

#pragma mark - Localization

- (void)relocalizeUI {
    _runScriptButton.toolTip = RPLoc(@"Script ausführen", @"Run Script");
    _runSelectionButton.toolTip = RPLoc(@"Auswahl ausführen", @"Run Selection");
    _stopButton.toolTip = RPLoc(@"Aktuellen Befehl abbrechen", @"Interrupt current command");
    _restartButton.toolTip = RPLoc(@"Sitzung neu starten", @"Restart Session");
    _bannerInstallButton.title = RPLoc(@"Installieren via Homebrew", @"Install via Homebrew");
}

#pragma mark - Public API

- (BOOL)sessionAlive {
    if (!_session) return NO;
    RunPwshSessionState s = _session.state;
    return s == RunPwshSessionStateStarting || s == RunPwshSessionStateReady || s == RunPwshSessionStateRunning;
}

- (void)startSessionWithExecutable:(NSString *)executable {
    if (!_session) {
        RunPwshBridgeTransport *transport = [[RunPwshBridgeTransport alloc] initWithBridge:_terminalBridge];
        _session = [[RunPwshSession alloc] initWithTransport:transport];
        __weak RunPwshPanelView *weakSelf = self;
        _session.onStateChange = ^(RunPwshSessionState state) {
            RunPwshPanelView *strongSelf = weakSelf;
            if (!strongSelf) return;
            [strongSelf setSessionActive:(state == RunPwshSessionStateRunning)];
            if (state == RunPwshSessionStateReady || state == RunPwshSessionStateStarting) {
                [strongSelf focusTerminal];
            }
            if (state == RunPwshSessionStateEnded) {
                [strongSelf feedText:[NSString stringWithFormat:@"\n[%@]\n",
                    RPLoc(@"Sitzung beendet – „Sitzung neu starten“ drücken", @"Session ended – press Restart Session")]];
            }
        };
    }
    [_session startWithExecutable:executable];
}

- (BOOL)runText:(NSString *)text {
    return [_session runText:text];
}

- (void)interruptSession { [_session interrupt]; }
- (void)restartSession { [_session restart]; }
- (void)terminateSession { [_session terminate]; }

- (void)focusTerminal {
    [_terminalBridge focus];
}

- (void)feedText:(NSString *)text {
    if (![NSThread isMainThread]) {
        dispatch_async(dispatch_get_main_queue(), ^{ [self feedText:text]; });
        return;
    }
    NSString *normalized = [text stringByReplacingOccurrencesOfString:@"\r\n" withString:@"\n"];
    normalized = [normalized stringByReplacingOccurrencesOfString:@"\n" withString:@"\r\n"];
    [_terminalBridge feedWithText:normalized];
}

- (void)setSessionActive:(BOOL)active {
    _stopButton.enabled = active;
    _stopButton.contentTintColor = active ? [NSColor systemRedColor] : [NSColor systemGrayColor];
}

- (void)showInstallBanner:(BOOL)show reason:(nullable NSString *)reason canInstall:(BOOL)canInstall {
    if (show) {
        _bannerLabel.stringValue = reason ?: RPLoc(@"PowerShell (pwsh) wurde nicht gefunden.", @"PowerShell (pwsh) was not found.");
        _bannerInstallButton.hidden = !canInstall;
    }
    _bannerHeightConstraint.constant = show ? 40 : 0;
    _banner.hidden = !show;
    [self setNeedsLayout:YES];
}

- (void)setStatusText:(NSString *)text {
    _statusLabel.stringValue = text ?: @"";
}

#pragma mark - Actions

- (void)runScriptClicked:(id)sender {
    if ([self.delegate respondsToSelector:@selector(runPwshPanelViewDidRequestRunScript:)]) {
        [self.delegate runPwshPanelViewDidRequestRunScript:self];
    }
}

- (void)runSelectionClicked:(id)sender {
    if ([self.delegate respondsToSelector:@selector(runPwshPanelViewDidRequestRunSelection:)]) {
        [self.delegate runPwshPanelViewDidRequestRunSelection:self];
    }
}

- (void)stopClicked:(id)sender {
    if ([self.delegate respondsToSelector:@selector(runPwshPanelViewDidRequestStop:)]) {
        [self.delegate runPwshPanelViewDidRequestStop:self];
    }
}

- (void)restartClicked:(id)sender {
    if ([self.delegate respondsToSelector:@selector(runPwshPanelViewDidRequestRestart:)]) {
        [self.delegate runPwshPanelViewDidRequestRestart:self];
    }
}

- (void)installClicked:(id)sender {
    if ([self.delegate respondsToSelector:@selector(runPwshPanelViewDidRequestInstallPwsh:)]) {
        [self.delegate runPwshPanelViewDidRequestInstallPwsh:self];
    }
}

@end
